#pragma once

namespace nrp
{

typedef enum 
{ 
	PT_UNKNOWN=0, 
	PT_GAME, PT_GAMEENGINE, PT_GENRE, 
	PT_SCENARIO, PT_LICENSE, PT_SCRIPTS, 
	PT_VIDEOTECH, PT_SOUNDTECH, PT_MINIGAME,
	PT_PHYSIC, PT_ADVTECH, PT_VIDEOQUALITY,
	PT_SOUNDQUALITY, PT_SCENARIOQUALITY,
	PT_PLUGIN, PT_GAMEBOXADDON,
	PT_LANGUAGE, PT_PLATFORM,
	PT_COUNT 
} PROJECT_TYPE;

}//end namespace nrp