#pragma once
#include <string>

std::string GlobalPeopleName[] =
{
	"Andrew", "Anthony", "Alexander", 
	"Austin", "Aidan", "Angel",
	"Aaron", "Adam", "Aiden",
	"Adrian", "Alex", "Ashton",
	"Antonio",  "Alejandro", "Brandon",
	"Benjamin", "Bryan", "Brian",
	"Blake", "Christopher",	"Connor",
	"Cameron", "Charles", "Carlos",
	"Cole", "Chase", "Christian",
	"Caleb", "Colin", "Cody",
	"Carter", "Daniel", "Dylan",
	"Dominic", "David", "Diego",
	"Devin", "Elijah", "Eric",
	"Ethan", "Evan", "Gabriel",
	"Gavin", "Hunter", "Hayden",
	"Isaac", "Ian", "Isaiah",
	"Jacob", "Jose", "Jordan",
	"Jayden", "Jesus", "Jesse",
	"James", "Jack", "Jason",
	"Julian", "Jeremiah", "Jake",
	"Joshua", "Joseph", "John",
	"Jonathan", "Justin", "Jackson",
	"Juan", "Jaden", "Kevin", 
	"Kyle", "Lucas", "Logan",
	"Luke", "Luis", "Landon", 
	"Matthew", "Mason", "Michael",
	"Miguel", "Nicholas", "Nathaniel",
	"Nathan", "Noah", "Owen",
	"Patrick", "Richard", "Ryan",
	"Robert", "Sean", "Samuel", 
	"Steven", "Sebastian", "Seth",
	"Tyler", "Thomas", "Timothy",
	"William", "Wyatt", "Xavier", "Zachary",
	0
};

std::string GlobalPeopleSurname[] = 
{
	"Abramson", "Hoggarth", "Adamson", "Holiday",
	"Adderiy", "Holmes", "Addington", "Howard",
	"Adrian", "Jacobson", "Albertson", "James",	
	"Aldridge",	"Jeff",	"Allford",	"Jenkin",
	"Alsopp", "Jerome", "Anderson", "Johnson",
	"Andrews",	"Jones",	"Archibald",	"Keat",	
	"Arnold",	"Kelly",	"Arthurs",		"Kendal",	
	"Atcheson",	"Kennedy",	"Attwood",	"Kennet",	
	"Audley",	"Kingsman",	"Austin",	"Kirk",	
	"Ayrton",	"Laird",	"Babcock",	"Lamberts",	"Backer",	"Larkins",	
	"Baldwin",	"Lawman",	"Bargeman",	"Leapman",	"Barnes",	"Leman",	
	"Barrington",	"Lewin",	"Bawerman",	"Little",
	"Becker",	"Livingston",	"Benson",	"Longman",	"Berrington",	"MacAdam",	
	"Birch",	"MacAlister",	"Bishop",	"MacDonald",	"Black",	"Macduff",	
	"Blare",	"Macey",	"Blomfield",	"Mackenzie",	"Boolman",	"Mansfield",
	"Bootman",	"Marlow",	"Bosworth",	"Marshman",	
	"Bradberry",	"Mason",	"Bradshaw",	"Mathews",	"Brickman",	"Mercer",	
	"Brooks",	"Michaelson",	"Brown",	"Miers",	"Bush",	"Miller",	
	"Calhoun",	"Miln",	"Campbell",	"Milton",	"Carey",	"Molligan",	
	"Carrington",	"Morrison",	"Carroll",	"Murphy",	"Carter",	"Nash",	 
	"Chandter",	"Nathan",	"Chapman",	"Neal",	
	"Charlson",	"Nelson",	"Chesterton",	"Nevill",	
	"Clapton",	"Nicholson",	"Clifford",	"Nyman",
	"Coleman",	"Oakman",	"Conors",	"Ogden",	
	"Cook",		"Oldman",	"Cramer",	"Oldridge",	"Крайтон",	
	"Croftoon",	"Osborne",	"Crossman",	"Oswald",	
	"Daniels",	"Otis",	"Davidson",	"Owen",	
	"Day",	"Page",	"Dean",	"Palmer",	"Derrick",	"Parkinson",
	"Dickinson",	"Parson",	"Dodson",	"Pass",	"Donaldson",	"Paterson",	
	"Donovan",	"Peacock",	"Douglas",	"Pearcy",	"Dowman",	"Peterson",	
	"Dutton",	"Philips",	"Duncan",	"Porter",	"Dunce",	"Quincy",	
	"Durham",	"Raleigh",	"Dyson",	"Ralphs",	"Eddington",	"Ramacey",	
	"Edwards",	"Reynolds",	"Ellington",	"Richards",	"Elmers",	"Roberts",	
	"Enderson",	"Roger",	"Erickson",	"Russel",	"Evans",	"Ryder",	
	"Faber",	"Salisburry",	"Fane",	"Salomon",	"Farmer",	"Samuels",	
	"Farrell",	"Saunder",	"Ferguson",	"Shackley",	"Finch",	"Sheldon",	
	"Fisher",	"Sherlock",	"Fitzgerald",	"Shorter",	"Flannagan",	"Simon",	
	"Flatcher",	"Simpson",	"Fleming",	"Smith",	"Ford",	"Stanley",	
	"Forman",	"Forster",	"Stevenson",	"Foster",	"Sykes",	
	"Francis",	"Taft",	"Fraser"	"Taylor",	"Freeman",	"Thomson",	
	"Fulton",	"Thorndike",	"Galbraith",	"Thornton",	"Gardner",	"Timmons",	
	"Garrison",	"Tracey",	"Gate",	"Turner",	
	"Gerald",	"Vance",	"Gibbs",	"Vaughan",	"Gilbert",	"Wainwright",
	"Gill",	"Walkman",	"Gilmore",	"Wallace",	"Gilson",	"Waller",	
	"Gimson",	"Walter",	"Goldman",	"Ward",	"Goodman",	"Warren",	
	"Gustman",	"Watson",	"Haig",	"Wayne",	"Hailey",	"Webster",	
	"Hamphrey",	"Wesley",	"Hancock",		"White",	"Hardman",	"WifKinson",	
	"Harrison",	"Winter",	"Hawkins",	"Wood",	
	"Higgins",	"Youmans",	"Hodge",	"Young"	
};