--[[
Ёти переменные св€заны с графическим движком.
!!!!!Ќ≈Ћ№«я ћ≈Ќя“№ »’ »ћ≈Ќј » «Ќј„≈Ќ»я!!!!!
--]]
ST_LINE_SERIE			= 0

CHNL_RFYZ				= "rfyz_src"
CHNL_RFYZ_ASRF			= "rfyz_src_rf"
CHNL_RFYZ_ASY			= "rfyz_src_y"
CHNL_RFYZ_ASZ			= "rfyz_src_z"
CHNL_IMAGE				= "image_src"

MAIN_CAMERA_NAME		= "_MainCameraName_"

AN_BOTTOM=0
AN_LEFT=1

EVENT_ADD_TO_LIST		= 1

EMF_LIGHTING			= 8 

SCENE_BEFORE_RENDER		= 10000
SCENE_AFTER_END			= 10001
SCENE_LMOUSE_LEFT_UP	= 10002
SCENE_TERMINATION		= 10003
SCENE_USER_EVENT		= 10004
SCENE_KEY_INPUT_EVENT	= 10005
SCENE_RMOUSE_LEFT_UP	= 10006
SCENE_MOUSE_MOVED		= 10007
SCENE_AFTER_RENDER		= 10008
SCENE_BEFORE_BEGIN		= 10009
SCENE_LMOUSE_DOUBLE_CLICK = 10010

GUIELEMENT_BEFORE_DRAW	= 11001
GUIELEMENT_AFTER_DRAW	= 11002